matrix:
  include:
    - language: c
      sudo: false
      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/newdigate/audio/master/extras/install-travis-ci-arduino.sh)
      install:
        - arduino --install-library "SerialFlash","MIDI Library","Adafruit SleepyDog Library","Adafruit FONA Library","Queue","SD","Adafruit GFX Library","Adafruit ST7735 Library","Encoder"
      script:
        - build_main_platforms

notifications:
  email:
    on_success: change
    on_failure: change