name: test
on:
  push:
    # branches: [main, master]
  pull_request:
    # branches: [main, master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        src:
          - examples/Analysis/DialTone_7segment
          - examples/Analysis/DialTone_Serial
          - examples/Analysis/FFT
          - examples/Analysis/PeakMeterMono
          - examples/Analysis/PeakMeterStereo
          - examples/Analysis/SpectrumAnalyzerBasic
          - examples/Effects/Bitcrusher
          - examples/Effects/Chorus
          - examples/Effects/Delay
          - examples/Effects/Filter
          - examples/Effects/Filter_FIR
          - examples/Effects/Flange
          - examples/HardwareTesting/PassThroughMono
          - examples/HardwareTesting/PassThroughStereo
          - examples/HardwareTesting/ToneSweep
          - examples/HardwareTesting/WM8731MikroSine
          - examples/MemoryAndCpuUsage
          - examples/Recorder
          - examples/SamplePlayer
          - examples/Synthesis/PlaySynthMusic
          - examples/Synthesis/pulseWidth
          - examples/Tutorial/Part_1_02_Hardware_Test
          - examples/Tutorial/Part_1_03_Playing_Music
          - examples/Tutorial/Part_1_04_Blink_While_Playing
          - examples/Tutorial/Part_1_05_Do_More_While_Playing
          - examples/WavFilePlayer
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - run: rm -r extras
      - run: pip install platformio
      # install dependent libraries
      # http://platformio.org/#!/lib/show/539/SerialFlash
      - run: platformio lib install 539
      # remove unused items
      # - run: ls -l ${{ matrix.src }}
      - env:
          PLATFORMIO_BUILD_FLAGS: -larm_cortexM4l_math
          PLATFORMIO_CI_SRC: ${{ matrix.src }}
        run: platformio ci --lib=. --board=teensy31
